<a href="https://colab.research.google.com/github/ahurara/Project/blob/main/python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
w1, w2, w3 = 0.3, 0.2, 0.5

kanto = np.array([73,67,43])
kanto

array([73, 67, 43])

In [ ]:
weights = np.array([w1,w2,w3])
weights

array([0.3, 0.2, 0.5])

In [ ]:
np.dot(kanto,weights)

56.8

In [ ]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

climate_data.shape

(5, 3)

In [ ]:
np.matmul(climate_data,weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [ ]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

## **working with a csv file**

In [ ]:
import urllib.request

In [ ]:
urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7fc74f02a920>)

In [ ]:
climate_data =np.genfromtxt("climate.txt",delimiter=',',skip_header=1)
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [ ]:
weights =np.array([.3,.2,.5])
yields =climate_data @ weights
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [ ]:
yields.shape

(10000,)

In [ ]:
climate_result =np.concatenate((climate_data,yields.reshape(10000,1)),axis=1)
climate_result

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [ ]:
np.savetxt(
    "climate_result.txt",
    climate_result,
      fmt='%.2f', 
    delimiter=',',
    header='temperature,rainfall,humidity,yeild_apples', 
    comments=''
)

In [ ]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])
arr3.shape

(3, 2, 4)

In [ ]:
ar2=np.zeros((4,2))
ar2

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])